export enum TokenType {
  Select = "SELECT",
  From = "FROM",
  Where = "WHERE",
  And = "AND",
  Or = "OR",
  Order = "ORDER",
  By = "BY",
  Asc = "ASC",
  Desc = "DESC",
  Limit = "LIMIT",
  Create = "CREATE",
  Table = "TABLE",
  Insert = "INSERT",
  Into = "INTO",
  Values = "VALUES",
  Update = "UPDATE",
  Set = "SET",
  Delete = "DELETE",
  Count = "COUNT",
  Sum = "SUM",
  Avg = "AVG",
  Min = "MIN",
  Max = "MAX",
  Group = "GROUP",
  Inner = "INNER",
  Left = "LEFT",
  Join = "JOIN",
  On = "ON",
  As = "AS",
  Is = "IS",
  Nulls = "NULLS",
  First = "FIRST",
  Last = "LAST",
  IntegerType = "INTEGER_TYPE",
  DecimalType = "DECIMAL_TYPE",
  TextType = "TEXT_TYPE",
  BooleanType = "BOOLEAN_TYPE",
  Primary = "PRIMARY",
  Key = "KEY",
  Foreign = "FOREIGN",
  References = "REFERENCES",
  Unique = "UNIQUE",
  Constraint = "CONSTRAINT",
  Begin = "BEGIN",
  Commit = "COMMIT",
  Rollback = "ROLLBACK",
  Transaction = "TRANSACTION",
  Save = "SAVE",
  Not = "NOT",
  Identifier = "IDENTIFIER",
  Integer = "INTEGER",
  Decimal = "DECIMAL",
  String = "STRING",
  True = "TRUE",
  False = "FALSE",
  Null = "NULL",
  Star = "STAR",
  Comma = "COMMA",
  Semicolon = "SEMICOLON",
  LeftParen = "LEFT_PAREN",
  RightParen = "RIGHT_PAREN",
  Equal = "EQUAL",
  NotEqual = "NOT_EQUAL",
  Greater = "GREATER",
  GreaterEqual = "GREATER_EQUAL",
  Less = "LESS",
  LessEqual = "LESS_EQUAL",
  Plus = "PLUS",
  Minus = "MINUS",
  Slash = "SLASH",
  Percent = "PERCENT",
  Dot = "DOT",
  Eof = "EOF"
}

export type TokenLiteral = string | number | boolean | null;

export interface Token {
  type: TokenType;
  lexeme: string;
  literal?: TokenLiteral;
  start: number;
  end: number;
}

export const KEYWORDS: ReadonlyMap<string, TokenType> = new Map([
  ["SELECT", TokenType.Select],
  ["FROM", TokenType.From],
  ["WHERE", TokenType.Where],
  ["AND", TokenType.And],
  ["OR", TokenType.Or],
  ["ORDER", TokenType.Order],
  ["BY", TokenType.By],
  ["ASC", TokenType.Asc],
  ["DESC", TokenType.Desc],
  ["LIMIT", TokenType.Limit],
  ["CREATE", TokenType.Create],
  ["TABLE", TokenType.Table],
  ["INSERT", TokenType.Insert],
  ["INTO", TokenType.Into],
  ["VALUES", TokenType.Values],
  ["UPDATE", TokenType.Update],
  ["SET", TokenType.Set],
  ["DELETE", TokenType.Delete],
  ["COUNT", TokenType.Count],
  ["SUM", TokenType.Sum],
  ["AVG", TokenType.Avg],
  ["MIN", TokenType.Min],
  ["MAX", TokenType.Max],
  ["GROUP", TokenType.Group],
  ["INNER", TokenType.Inner],
  ["LEFT", TokenType.Left],
  ["JOIN", TokenType.Join],
  ["ON", TokenType.On],
  ["AS", TokenType.As],
  ["IS", TokenType.Is],
  ["NULLS", TokenType.Nulls],
  ["FIRST", TokenType.First],
  ["LAST", TokenType.Last],
  ["INTEGER", TokenType.IntegerType],
  ["DECIMAL", TokenType.DecimalType],
  ["TEXT", TokenType.TextType],
  ["BOOLEAN", TokenType.BooleanType],
  ["PRIMARY", TokenType.Primary],
  ["KEY", TokenType.Key],
  ["FOREIGN", TokenType.Foreign],
  ["REFERENCES", TokenType.References],
  ["UNIQUE", TokenType.Unique],
  ["CONSTRAINT", TokenType.Constraint],
  ["BEGIN", TokenType.Begin],
  ["COMMIT", TokenType.Commit],
  ["ROLLBACK", TokenType.Rollback],
  ["TRANSACTION", TokenType.Transaction],
  ["SAVE", TokenType.Save],
  ["NOT", TokenType.Not],
  ["TRUE", TokenType.True],
  ["FALSE", TokenType.False],
  ["NULL", TokenType.Null]
]);
